# Generated by Django 4.2.5 on 2023-09-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeId', models.CharField(max_length=100)),
                ('fullName', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
    ]
