# Generated by Django 4.1.7 on 2023-10-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.CharField(default=2000, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeId',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
