# Generated by Django 4.2.5 on 2023-10-03 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_employee_id_employee_projects_employee_salary_and_more'),
    ]

    operations = [
    ]
